title: B1udg3r
email: bludger@bludger.dev
description: >-
  Security Consultant & Researcher specializing in radio frequency protocols,
  infrastructure security, and web application logic flaws.
baseurl: ""
url: "https://bludger.dev"
twitter_username: B1udg3r
github_username: B1udg3r

remote_theme: abhinavs/moonwalk

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Clean URLs for better Google ranking
permalink: /:categories/:title/
